stages:
  - build
  - run
  - lint
  - test
  - cleanup
  - deploy

build-job:
  stage: build
  script:
    - docker compose -f docker-compose.yaml build

run-job:
  stage: run
  needs: [build-job]
  script:
    - docker compose -f docker-compose.yaml up -d

lint-test-job:
  stage: lint
  needs: [run-job]
  script:
    - echo "Проверка форматирования кода с помощью ruff..."
    - docker compose exec -it candy_store ruff format --config ruff.toml --check app tests

    - echo "Проверка типов с помощью pyright..."
    - docker compose exec -it candy_store pyright app tests

    - echo "Проверка стиля кода с помощью ruff..."
    - docker compose exec -it candy_store ruff check --config ruff.toml app tests

    - echo "Проверка сортировки импортов с помощью isort..."
    - docker compose exec -it candy_store isort --check-only --diff app tests

test-job:
  stage: test
  needs: [lint-test-job]
  script:
    - echo "Начало тестирования"
    - docker compose exec candy_store pytest -s -v


cleanup-job:
  stage: cleanup
  needs: [run-job, test-job]
  script:
    - docker compose -f docker-compose.yaml down
    - docker container prune -f
    - docker volume prune -f
    - docker system prune -f
  when: always


deploy-job:
  stage: deploy
  needs: [test-job]
  script:
    - docker compose -f docker-compose.yaml build
    - docker compose -f docker-compose.yaml up -d
  when: manual
