"""empty message

Revision ID: 07e3939b1495
Revises: 8f11c081474d
Create Date: 2025-07-14 14:56:21.700280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '07e3939b1495'
down_revision: Union[str, Sequence[str], None] = '8f11c081474d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='unitenum',
        new_values=['PIECES', 'KILOGRAMS'],
        affected_columns=[TableReference(table_schema='public', table_name='products', column_name='unit')],
        enum_values_to_rename=[("KGS", "KILOGRAMS")],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='unitenum',
        new_values=['PIECES', 'KGS'],
        affected_columns=[TableReference(table_schema='public', table_name='products', column_name='unit')],
        enum_values_to_rename=[("KILOGRAMS", "KGS")],
    )
    # ### end Alembic commands ###
