"""Add address status

Revision ID: 11b79d35cf26
Revises: 8fcd48959d15
Create Date: 2025-07-30 16:07:49.433867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b79d35cf26'
down_revision: Union[str, Sequence[str], None] = '8fcd48959d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('status', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'cartsItems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cartsItems', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'favourites', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'favourites', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_column('addresses', 'status')
    # ### end Alembic commands ###
