"""empty message

Revision ID: 1a745122c7d8
Revises: 14394c06a438
Create Date: 2025-07-17 08:39:39.785155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a745122c7d8'
down_revision: Union[str, Sequence[str], None] = '14394c06a438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'addresses', ['address'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
