"""Добавил Purchases

Revision ID: 365d60c731cf
Revises: 11b79d35cf26
Create Date: 2025-08-02 21:48:22.920295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365d60c731cf'
down_revision: Union[str, Sequence[str], None] = '11b79d35cf26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cartsItems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cartsItems', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    # ### end Alembic commands ###
