"""empty message

Revision ID: 4aa3f3a44485
Revises: 1a745122c7d8
Create Date: 2025-07-21 10:03:56.246458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa3f3a44485'
down_revision: Union[str, Sequence[str], None] = '1a745122c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cartsItems', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cartsItems', 'carts', ['cart_id'], ['id'])
    #op.add_column('users', sa.Column('user_chat_id', sa.Integer(), nullable=False))
    #op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    #op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    #op.create_unique_constraint(None, 'users', ['user_chat_id'])
    #op.drop_column('users', 'email')
    #op.drop_column('users', 'surname')
    #op.drop_column('users', 'hashed_password')
    #op.drop_column('users', 'name')
    #op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'user_chat_id')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    # ### end Alembic commands ###
