"""empty message

Revision ID: 7dc544a0ea56
Revises: 8030be0284a6
Create Date: 2025-07-11 00:25:57.558265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc544a0ea56'
down_revision: Union[str, Sequence[str], None] = '8030be0284a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('date_receiving', sa.Date(), nullable=False),
    sa.Column('receiving_method', postgresql.ENUM('PICKUP', 'DELIVERY', name='receivingmethodenum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('payment', postgresql.ENUM('CASH', 'NONCASH', name='paymentmethodenum'), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING', 'PREPARING', 'READY', 'DELIVERY', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
