"""empty message

Revision ID: 98c6eb459bc0
Revises: 51565cb5e047
Create Date: 2025-07-16 19:02:25.368631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c6eb459bc0'
down_revision: Union[str, Sequence[str], None] = '51565cb5e047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time_receiving', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time_receiving')
    # ### end Alembic commands ###
