"""empty message

Revision ID: b27cbc229bf8
Revises: 7dc544a0ea56
Create Date: 2025-07-13 12:42:08.733984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27cbc229bf8'
down_revision: Union[str, Sequence[str], None] = '7dc544a0ea56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    # ### end Alembic commands ###
