"""empty message

Revision ID: b86674a87626
Revises: 31df4f7ba3db
Create Date: 2025-07-23 20:04:36.074754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b86674a87626'
down_revision: Union[str, Sequence[str], None] = '31df4f7ba3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #sa.Enum('ACTIVE', 'INACTIVE', name='statuscartenum').create(op.get_bind())
    #op.add_column('carts', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='statuscartenum', create_type=False), nullable=False))
    op.create_foreign_key(None, 'cartsItems', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'cartsItems', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_column('carts', 'status')
    sa.Enum('ACTIVE', 'INACTIVE', name='statuscartenum').drop(op.get_bind())
    # ### end Alembic commands ###
