"""empty message

Revision ID: d20653e986ee
Revises: b86674a87626
Create Date: 2025-07-29 13:44:57.613449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd20653e986ee'
down_revision: Union[str, Sequence[str], None] = 'b86674a87626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='statusproductenum').create(op.get_bind())
    op.create_foreign_key(None, 'cartsItems', 'carts', ['cart_id'], ['id'])
    op.create_foreign_key(None, 'cartsItems', 'products', ['product_id'], ['id'])
    op.add_column('products', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='statusproductenum', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    op.drop_constraint(None, 'cartsItems', type_='foreignkey')
    sa.Enum('ACTIVE', 'INACTIVE', name='statusproductenum').drop(op.get_bind())
    # ### end Alembic commands ###
